spring.application.name=senac

## conexão com o banco de dados postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/senac
spring.datasource.username=postgres
spring.datasource.password=123

## configuração do hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

## configuração do swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
